### ISSUE TITLE
Request: php

### ISSUE THREAD

**Issue by robdecker** [gkemmey/jekyll-syntax-highlighting#1]
Love the package! Could you add php highlighting?

**Comment by gkemmey** [comment]
Hmmm there's at least an attempt to support PHP:

https://github.com/gkemmey/jekyll-syntax-highlighting/blob/master/grammars/jekyll-syntax-highlighting.cson#L243-L259

I know we piggyback off how the `language-gfm` package handles this, and it doesn't appear to be working quite right there either (at least not for me quickly testing):

![image](https://user-images.githubusercontent.com/1423258/31799261-0406721a-b507-11e7-9a4d-c392378741b1.png)

I'll try and take a closer look this weekend, see if I can figure out what's going on.

**Comment by gkemmey** [comment]
Update: @robdecker here's as far as I've gotten so far: https://github.com/gkemmey/jekyll-syntax-highlighting/pull/2
